name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      FLUTTER_VERSION: "3.10.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+02:00"
      - run: echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > android/app/key.jks
      - run: flutter build apk --release --build-name=${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }} --build-number=${{github.run_number}}
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
          SIGNING_KEY_PATH: key.jks
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.${{github.run_number}}
          message: "Latest release"
