name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      FLUTTER_VERSION: "3.10.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+02:00"
      - run: echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > android/app/key.jks
      - run: flutter build apk --release --build-name=${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }} --build-number=${{github.run_number}}
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
          SIGNING_KEY_PATH: key.jks
      - uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: Vocazione-Francescana/Assistente-Spirituale
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: build/app/outputs/flutter-apk/app-release.apk
          notifyTesters: false
          debug: false
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.${{github.run_number}}
          message: "Latest release"
      - run: flutter build web
#      - name: Deploy to Netlify
#        uses: nwtgck/actions-netlify@v1.1
#        with:
#          publish-dir: './build/web'
#          production-branch: master
#        env:
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#        timeout-minutes: 1
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASSISTENTE_SPIRITUALE }}'
          channelId: live
